yosimitso_working_forum:
    resource: "@YosimitsoWorkingForumBundle/Resources/config/routing.yml"
    prefix:   /forum
    #index:
#    path: /
#    controller: App\Controller\DefaultController::index
